#release configuration
#Mon Aug 10 12:19:27 CEST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.net.imglib2\:imglib2-mesh=1.2.1-SNAPSHOT
project.rel.net.imglib2\:imglib2-mesh=1.2.0
project.scm.net.imglib2\:imglib2-mesh.connection=scm\:git\:https\://github.com/imglib/imglib2-mesh
project.scm.net.imglib2\:imglib2-mesh.developerConnection=scm\:git\:git@github.com\:imglib/imglib2-mesh
project.scm.net.imglib2\:imglib2-mesh.tag=HEAD
project.scm.net.imglib2\:imglib2-mesh.url=https\://github.com/imglib/imglib2-mesh
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=imglib2-mesh-1.2.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/imglib/imglib2-mesh
